[www]
user = www-data
group = www-data
pm = dynamic
pm.max_children = ${PHPFPM_MAX_CHILDREN}
pm.start_servers = ${PHPFPM_START_SERVERS}
pm.min_spare_servers = ${PHPFPM_MIN_SPARE_SERVERS}
pm.max_spare_servers = ${PHPFPM_MAX_SPARE_SERVERS}
